### ISSUE TITLE
Buying: paying the current owner and setting the new valuation should be separated

### ISSUE THREAD

**Issue by will-holley** [721labs/partial-common-ownership#36]
Situation:

Buyer wants to set a higher self-assessed value but only pay the current owner their self assessed value.

Currently:

Buyer can buy at a price higher than the current owner's price; the current owner receives the entire amount.  e.g. `current = 1; new = 1.5; remit = 1.5`

Proposed Solutions:

- current = 1; new = 1.5; only remit 1; add 0.5 to deposit?

**Comment by vicsn** [comment]
Within the current `buy` model, to me it would indeed make the most sense to only let the buyer pay the current price. There is no rational incentive to pay more than the current price.

The current design could be worked around by buyers by only purchasing at `currentPrice + 1wei` then setting the price higher.

**Comment by will-holley** [comment]
The current rational incentive is to allow raising the price in a single transaction so the previous owner does not immediately swoop in and re-purchase it.  

I've added the **bug** label as increasing price should be a separate behavior and currently exists as a (technically convenient or inconvenient, depending on your perspective and the current price) side effect.

**Comment by will-holley** [comment]
https://github.com/721labs/partial-common-ownership/pull/52
