### ISSUE TITLE
Consider basing _taxOwed on all historic prices

### ISSUE THREAD

**Issue by vicsn** [721labs/partial-common-ownership#41]
`_taxOwed` is only calculated based on the current price, not on all previous prices. Depending on the frequency of tax collection, this can lead to missing tax paid. Someone could set a high price for a long time period, only to lower it just before `_taxOwed` is checked.

**Comment by will-holley** [comment]
Calling `#changePrice` collects tax at the current rate prior to updating the price, which prevents the mentioned scenario.

I'm not following "depending on the frequency of tax collection, this can lead to missing tax paid."  – can you expound on this?

**Comment by vicsn** [comment]
Apologies, I overlooked the `_collectTax` modifier! That should work just fine.
