### ISSUE TITLE
Keeping the dependency graph clean

### ISSUE THREAD

**Issue by vicsn** [721labs/partial-common-ownership#57]
I used [surya](https://github.com/ConsenSys/surya) to get a better understanding of the new module setup, I think it may be worth to use regularly, perhaps making it (or a related utility) part of a new testing command. 

Personally I think its best to limit the abstractions as much as possible. But its a fine line. Within the current setup its at least worth considering not to:
- let both `PartialCommonOwnership721` and `TokenManagement` inherit from `ERC721`
- let both `PartialCommonOwnership721` and `Taxation` inherit from `Valuation`

Command used: `./bin/surya inheritance partial-common-ownership/contracts/**/*.sol partial-common-ownership/contracts/token/modules/*.sol | dot -Tpng > MyContract.png` 

![MyContract](https://user-images.githubusercontent.com/24724627/153077180-7a67a07c-29f7-47fe-9ed6-0ad6f4dddb94.png)

**Comment by will-holley** [comment]
Agreed

**Comment by will-holley** [comment]
As we get into alternative implementations, these modules will improve, but I think f48742ddfaf767feaa7f75bba0d5ff7dd6f68ff4 and f1b19965d3d9c4bd68eae854428f93e73c62a7d are satisfactory for now.

![deps](https://user-images.githubusercontent.com/8657791/162596733-38d6dc8c-e468-452d-8d86-03fe58274d1f.png)
